image: registry.gitlab.com/anagolay/docker-images/gitpod-workspace:gitpod_workspace-full_2022-05-08-14-31-53_experimental
tasks:
  - name: Setup env
    command: bash $GITPOD_REPO_ROOT/.devops/gitpod/start-cmd.sh && exit

ports:
  - port: 4226
    visibility: private
    onOpen: ignore
  - port: 30333
    visibility: private
    onOpen: ignore
  - port: 9933
    visibility: private
    onOpen: ignore
  - port: 9944
    visibility: private
    onOpen: ignore
  - port: 9615
    visibility: private
    onOpen: ignore

vscode:
  extensions:
    - rust-lang.rust
    - tamasfe.even-better-toml
    # - belfz.search-crates-io
    - serayuzgur.crates
    - vadimcn.vscode-lldb
    - redhat.vscode-yaml
    - mhutchie.git-graph
