coverage:
  stage: extras
  allow_failure: true
  # coverage: /^\d+.\d+% coverage/ # tarpaulin
  coverage: /\s*lines\.*:\s*([\d\.]+%)/
  rules:
    - !reference [.rule-friendly-word, rules]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - rust
  needs: ["test_flow"]
  # cache: {}
  variables:
    LLVM_PROFILE_FILE: "anagolay-%p-%m.profraw"
  before_script:
    - !reference [.info-compiler, before_script]
    # - unset SCCACHE_BUCKET
    # - unset SCCACHE_ENDPOINT
    # - unset AWS_ACCESS_KEY_ID
    # - unset AWS_SECRET_ACCESS_KEY
    - unset BUILD_CACHE_FILE # disable the build cache aka target
    - !reference [.with-local-cachier, before_script]
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:test\r\e[0KCode coverage phase"

    - makers coverage-grcov

    - sccache --show-stats
    - echo -e "\e[0Ksection_end:`date +%s`:test\r\e[0K"
  # when: manual
  artifacts:
    when: on_success
    paths:
      - "coverage"
    expire_in: 2 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
