// This file is part of Anagolay Network.

// Copyright (C) 2019-2023 Anagolay Network.

//! Autogenerated weights for operations
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-10, STEPS: `50`, REPEAT: 100, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/anagolay
// benchmark
// pallet
// --chain
// dev
// --steps
// 50
// --repeat
// 100
// --pallet
// operations
// --extrinsic
// *
// --execution
// wasm
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// ./pallets/operations/src/weights.rs
// --template
// ./templates/module-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{
  sp_std::marker::PhantomData,
  traits::Get,
  weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for operations.
pub trait WeightInfo {
  fn create() -> Weight;
  fn version_approve() -> Weight;
}

/// Weights for operations using the Substrate node and recommended hardware.
pub struct AnagolayWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for AnagolayWeight<T> {
  // Storage: Operations OperationByOperationIdAndAccountId (r:1 w:1)
  // Storage: Operations VersionIdsByOperationId (r:1 w:1)
  // Storage: Anagolay ArtifactsByArtifactId (r:1 w:1)
  // Storage: Operations Total (r:1 w:1)
  // Storage: Timestamp Now (r:1 w:0)
  // Storage: Operations VersionByVersionId (r:0 w:1)
  fn create() -> Weight {
    (105_420_000 as Weight)
      .saturating_add(T::DbWeight::get().reads(5 as Weight))
      .saturating_add(T::DbWeight::get().writes(5 as Weight))
  }
  fn version_approve() -> Weight {
    (8_530_000 as Weight)
  }
}

// For backwards compatibility and tests
impl WeightInfo for () {
  // Storage: Operations OperationByOperationIdAndAccountId (r:1 w:1)
  // Storage: Operations VersionIdsByOperationId (r:1 w:1)
  // Storage: Anagolay ArtifactsByArtifactId (r:1 w:1)
  // Storage: Operations Total (r:1 w:1)
  // Storage: Timestamp Now (r:1 w:0)
  // Storage: Operations VersionByVersionId (r:0 w:1)
  fn create() -> Weight {
    (105_420_000 as Weight)
      .saturating_add(RocksDbWeight::get().reads(5 as Weight))
      .saturating_add(RocksDbWeight::get().writes(5 as Weight))
  }
  fn version_approve() -> Weight {
    (8_530_000 as Weight)
  }
}
