.use-kaniko-base:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

.use-kaniko:
  extends: .use-kaniko-base
  script:
    - set -ex
    - >-
      /kaniko/executor
      --cache=true
      --cache-copy-layers
      --build-arg "GIT_LAST_REVISION=${GIT_LAST_REVISION}"
      --reproducible
      --context "${KANIKO_CONTEXT}"
      --dockerfile "${IMAGE_DOCKERFILE_PATH}"
      --destination "${IMAGE_NAME}"

.use-kaniko-with-latest:
  extends: .use-kaniko-base
  script:
    - >-
      /kaniko/executor
      --cache=true
      --cache-copy-layers
      --reproducible
      --build-arg "GIT_LAST_REVISION=${GIT_LAST_REVISION}"
      --context "${KANIKO_CONTEXT}"
      --dockerfile "${IMAGE_DOCKERFILE_PATH}"
      --destination "${IMAGE_NAME}"
