// This file is part of Anagolay Network.

// Copyright (C) 2019-2023 Anagolay Network.

//! Autogenerated weights for poe
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-10, STEPS: `50`, REPEAT: 100, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/anagolay
// benchmark
// pallet
// --chain
// dev
// --steps
// 50
// --repeat
// 100
// --pallet
// poe
// --extrinsic
// *
// --execution
// wasm
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// ./pallets/poe/src/weights.rs
// --template
// ./templates/module-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{
  sp_std::marker::PhantomData,
  traits::Get,
  weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions needed for poe.
pub trait WeightInfo {
  fn create_proof() -> Weight;
  fn save_phash() -> Weight;
}

/// Weights for poe using the Substrate node and recommended hardware.
pub struct AnagolayWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for AnagolayWeight<T> {
  // Storage: Workflows WorkflowByWorkflowIdAndAccountId (r:2 w:0)
  // Storage: Poe ProofByProofIdAndAccountId (r:1 w:1)
  // Storage: Poe ProofTotal (r:1 w:1)
  fn create_proof() -> Weight {
    (48_430_000 as Weight)
      .saturating_add(T::DbWeight::get().reads(4 as Weight))
      .saturating_add(T::DbWeight::get().writes(2 as Weight))
  }
  // Storage: Poe ProofByProofIdAndAccountId (r:1 w:0)
  // Storage: Poe PhashByHashAndAccountId (r:1 w:1)
  // Storage: Poe PhashTotal (r:1 w:1)
  fn save_phash() -> Weight {
    (42_340_000 as Weight)
      .saturating_add(T::DbWeight::get().reads(3 as Weight))
      .saturating_add(T::DbWeight::get().writes(2 as Weight))
  }
}

// For backwards compatibility and tests
impl WeightInfo for () {
  // Storage: Workflows WorkflowByWorkflowIdAndAccountId (r:2 w:0)
  // Storage: Poe ProofByProofIdAndAccountId (r:1 w:1)
  // Storage: Poe ProofTotal (r:1 w:1)
  fn create_proof() -> Weight {
    (48_430_000 as Weight)
      .saturating_add(RocksDbWeight::get().reads(4 as Weight))
      .saturating_add(RocksDbWeight::get().writes(2 as Weight))
  }
  // Storage: Poe ProofByProofIdAndAccountId (r:1 w:0)
  // Storage: Poe PhashByHashAndAccountId (r:1 w:1)
  // Storage: Poe PhashTotal (r:1 w:1)
  fn save_phash() -> Weight {
    (42_340_000 as Weight)
      .saturating_add(RocksDbWeight::get().reads(3 as Weight))
      .saturating_add(RocksDbWeight::get().writes(2 as Weight))
  }
}
